spring:
  application:
    name: Effective-Mobile-RestAPI

  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    driver-class-name: org.postgresql.Driver
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  security:
    jwt:
      secret-key: my-secret-key
      expiration-time: 86400000